# Generated by Django 3.2.16 on 2024-05-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240513_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': '%(class)ss'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': '%(class)ss'},
        ),
    ]
