# Generated by Django 3.2.16 on 2024-05-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240514_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': '%(class)ss', 'ordering': ('created', 'author')},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('following',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': '%(class)ss', 'ordering': ('-pub_date', 'author')},
        ),
    ]
