# Generated by Django 3.2.16 on 2024-05-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240514_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': '%(class)ss', 'ordering': ('-pub_date',)},
        ),
    ]
