# Generated by Django 3.2.16 on 2024-05-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': '%(class)ss', 'ordering': ('pub_date', 'author')},
        ),
    ]
